pipeline {
       agent any

	tools {
		python 'Python 3.7'  // Use ShiningPanda to define this tool in Jenkins
	}

	environment {
		VENV_DIR = 'venv'
	}

	stages {
		stage('Clone Repo') {
			steps {
				git credentialsId: 'github-creds',
					url: 'https://github.com/Pritchad25/messaging_app.git'
			}
		}

		stage('Install Dependencies') {
			steps {
				sh 'python3 -m venv $VENV_DIR'
				sh './$VENV_DIR/bin/pip install --upgrade pip'
				sh './$VENV_DIR/bin/pip install -r requirements.txt'
			}
		}

		stage('Run Tests') {
			steps {
				sh './$VENV_DIR/bin/pytest --junitxml=report.xml'
			}
		}

		stage('Archive Report') {
			steps {
				junit 'report.xml'
			}
		}
	}

	triggers {
		// Manual only trigger; omit SCM or timer triggers
	}
}
